language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "nightly" # currently points to 3.6-dev
install: "pip install -r travis-requirements.txt"
script: "pytest tests"
